name: Dependency Update Release

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: PNPM build
        run: pnpm run build

      - name: Set Changelog
        run: |
          git config --local user.email "zjphchenxueli@163.com"
          git config --local user.name "chenxueli"

      - name: PNPM bumpp
        run: pnpm run bumpp

      - name: Publish to NPM
        run: pnpm run publish:release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
